name: Run every 5 min

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes

jobs:
  cron:
    name: Run every 5 minutes
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world"
